### PR TITLE
fix: LES data source

### PR DESCRIPTION
**Pull request by haakon-e**
I moved the LES data for plotting to my personal OneDrive account where it can stay for eternity.

Also cleaned up the relevant code a bit.

### CODE REVIEW

**Comment by ilopezgp** [comment]
Is there a problem with the current Dropbox? Anyway, if we can keep LES results in the OneDrive you provided, this looks good to me.

**Comment by haakon-e** [comment]
Switched storage to google drive due to authentication token issues.

@ilopezgp Yes. there was a problem with the current links. Doing some final tests now, and this should be good.

**Comment by ilopezgp** [comment]
LGTM, but probably best to wait for Yair to check since he uses these scripts more often. Thanks!

**Review by ilopezgp — APPROVED** [review]

**Comment by ilopezgp** [comment]
Also, I think that this implementation does not raise errors if the directories already exist. It might be safer to set `exist_ok` to false.

**Pull request merged**
